using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class MuteSyncModel
{
    [RealtimeProperty(1, true, true)]
    private bool _mute;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class MuteSyncModel : RealtimeModel {
    public bool mute {
        get {
            return _muteProperty.value;
        }
        set {
            if (_muteProperty.value == value) return;
            _muteProperty.value = value;
            InvalidateReliableLength();
            FireMuteDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(MuteSyncModel model, T value);
    public event PropertyChangedHandler<bool> muteDidChange;
    
    public enum PropertyID : uint {
        Mute = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _muteProperty;
    
    #endregion
    
    public MuteSyncModel() : base(null) {
        _muteProperty = new ReliableProperty<bool>(1, _mute);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _muteProperty.UnsubscribeCallback();
    }
    
    private void FireMuteDidChange(bool value) {
        try {
            muteDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _muteProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _muteProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Mute: {
                    changed = _muteProperty.Read(stream, context);
                    if (changed) FireMuteDidChange(mute);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _mute = mute;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
