using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class OngoingCallModel
{

    [RealtimeProperty(1, true, true)]   private int _callerID;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class OngoingCallModel : RealtimeModel {
    public int callerID {
        get {
            return _callerIDProperty.value;
        }
        set {
            if (_callerIDProperty.value == value) return;
            _callerIDProperty.value = value;
            InvalidateReliableLength();
            FireCallerIDDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(OngoingCallModel model, T value);
    public event PropertyChangedHandler<int> callerIDDidChange;
    
    public enum PropertyID : uint {
        CallerID = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _callerIDProperty;
    
    #endregion
    
    public OngoingCallModel() : base(null) {
        _callerIDProperty = new ReliableProperty<int>(1, _callerID);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _callerIDProperty.UnsubscribeCallback();
    }
    
    private void FireCallerIDDidChange(int value) {
        try {
            callerIDDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _callerIDProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _callerIDProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.CallerID: {
                    changed = _callerIDProperty.Read(stream, context);
                    if (changed) FireCallerIDDidChange(callerID);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _callerID = callerID;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
