using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class PlayerSyncModel
{
    [RealtimeProperty(3, true, true)]   private bool _isRinging;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class PlayerSyncModel : RealtimeModel {
    public bool isRinging {
        get {
            return _isRingingProperty.value;
        }
        set {
            if (_isRingingProperty.value == value) return;
            _isRingingProperty.value = value;
            InvalidateReliableLength();
            FireIsRingingDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(PlayerSyncModel model, T value);
    public event PropertyChangedHandler<bool> isRingingDidChange;
    
    public enum PropertyID : uint {
        IsRinging = 3,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _isRingingProperty;
    
    #endregion
    
    public PlayerSyncModel() : base(null) {
        _isRingingProperty = new ReliableProperty<bool>(3, _isRinging);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _isRingingProperty.UnsubscribeCallback();
    }
    
    private void FireIsRingingDidChange(bool value) {
        try {
            isRingingDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _isRingingProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _isRingingProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.IsRinging: {
                    changed = _isRingingProperty.Read(stream, context);
                    if (changed) FireIsRingingDidChange(isRinging);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _isRinging = isRinging;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
