using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TestModel
{
    [RealtimeProperty(1, true, true)] private int _handAnimation;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TestModel : RealtimeModel {
    public int handAnimation {
        get {
            return _handAnimationProperty.value;
        }
        set {
            if (_handAnimationProperty.value == value) return;
            _handAnimationProperty.value = value;
            InvalidateReliableLength();
            FireHandAnimationDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TestModel model, T value);
    public event PropertyChangedHandler<int> handAnimationDidChange;
    
    public enum PropertyID : uint {
        HandAnimation = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _handAnimationProperty;
    
    #endregion
    
    public TestModel() : base(null) {
        _handAnimationProperty = new ReliableProperty<int>(1, _handAnimation);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _handAnimationProperty.UnsubscribeCallback();
    }
    
    private void FireHandAnimationDidChange(int value) {
        try {
            handAnimationDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _handAnimationProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _handAnimationProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.HandAnimation: {
                    changed = _handAnimationProperty.Read(stream, context);
                    if (changed) FireHandAnimationDidChange(handAnimation);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _handAnimation = handAnimation;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
