using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class UserScoreModel
{
    [RealtimeProperty(1, true, false)]
    private int _score;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class UserScoreModel : RealtimeModel {
    public int score {
        get {
            return _scoreProperty.value;
        }
        set {
            if (_scoreProperty.value == value) return;
            _scoreProperty.value = value;
            InvalidateReliableLength();
        }
    }
    
    public enum PropertyID : uint {
        Score = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _scoreProperty;
    
    #endregion
    
    public UserScoreModel() : base(null) {
        _scoreProperty = new ReliableProperty<int>(1, _score);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _scoreProperty.UnsubscribeCallback();
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _scoreProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _scoreProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Score: {
                    changed = _scoreProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _score = score;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
