using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class CallSyncModel
{
    [RealtimeProperty(1, true, true)] private int _dialingPlayer;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class CallSyncModel : RealtimeModel {
    public int dialingPlayer {
        get {
            return _dialingPlayerProperty.value;
        }
        set {
            if (_dialingPlayerProperty.value == value) return;
            _dialingPlayerProperty.value = value;
            InvalidateReliableLength();
            FireDialingPlayerDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(CallSyncModel model, T value);
    public event PropertyChangedHandler<int> dialingPlayerDidChange;
    
    public enum PropertyID : uint {
        DialingPlayer = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _dialingPlayerProperty;
    
    #endregion
    
    public CallSyncModel() : base(null) {
        _dialingPlayerProperty = new ReliableProperty<int>(1, _dialingPlayer);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _dialingPlayerProperty.UnsubscribeCallback();
    }
    
    private void FireDialingPlayerDidChange(int value) {
        try {
            dialingPlayerDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _dialingPlayerProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _dialingPlayerProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.DialingPlayer: {
                    changed = _dialingPlayerProperty.Read(stream, context);
                    if (changed) FireDialingPlayerDidChange(dialingPlayer);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _dialingPlayer = dialingPlayer;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
